name:                haskell-uon
version:             0.1.3.0
github:              "mejgun/haskell-uon"
license:             MIT
author:              "mejgun"
maintainer:          "example@example.com"
copyright:           "mejgun"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/mejgun/haskell-uon#readme>

dependencies:
- base >= 4.7 && < 5

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  language:            GHC2021
  dependencies:
    - time
    - req
    - text
    - aeson
    - html-entities
    - unordered-containers
    - http-client
    - bytestring
    - vector
    - scientific
  default-extensions:
    - OverloadedStrings
    - NoFieldSelectors
    - OverloadedRecordDot
    - DuplicateRecordFields

tests:
  haskell-uon-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-uon
